NEWLINE = b"\r\n"
HTTP_1_0 = "HTTP/1.0"
HTTP_1_1 = "HTTP/1.1"

METHOD_GET = "GET"
METHOD_HEAD = "HEAD"
METHOD_POST = "POST"
METHOD_PUT = "PUT"
METHOD_DELETE = "DELETE"
METHOD_CONNECT = "CONNECT"
METHOD_OPTIONS = "OPTIONS"
METHOD_PATCH = "PATCH"
METHODS = frozenset((
    METHOD_GET, METHOD_HEAD,
    METHOD_POST, METHOD_PUT,
    METHOD_DELETE, METHOD_CONNECT,
    METHOD_OPTIONS, METHOD_PATCH,
))
